In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
np.array([1.34,1,2,4])

array([1.34, 1.  , 2.  , 4.  ])

In [5]:
np.array([1,3,2,4],dtype = float)

array([1., 3., 2., 4.])

In [6]:
a1 = np.array([1,2,3,4])

In [8]:
a2 = np.array([[1,2,3],[4,5,6]])

In [9]:
type(a2)

numpy.ndarray

In [10]:
type(a1)

numpy.ndarray

In [11]:
a2.shape

(2, 3)

In [12]:
a2.ndim

2

In [14]:
a2.dtype

dtype('int32')

## create numpy array

In [18]:
np.zeros([2,4],dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
np.ones([5,6],dtype = int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [20]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.full([3,5],6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [22]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

## Random

In [23]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [24]:
np.random.normal(0,1,(3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [25]:
np.random.randint(0,10,(4,5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

In [27]:
np.random.rand(5,7)

array([[0.65314004, 0.17090959, 0.35815217, 0.75068614, 0.60783067,
        0.32504723, 0.03842543],
       [0.63427406, 0.95894927, 0.65279032, 0.63505887, 0.99529957,
        0.58185033, 0.41436859],
       [0.4746975 , 0.6235101 , 0.33800761, 0.67475232, 0.31720174,
        0.77834548, 0.94957105],
       [0.66252687, 0.01357164, 0.6228461 , 0.67365963, 0.971945  ,
        0.87819347, 0.50962438],
       [0.05571469, 0.45115921, 0.01998767, 0.44171092, 0.97958673,
        0.35944446, 0.48089353]])

## Array index and Slicing

In [37]:
x1 = np.random.randint(10,size = 10)
x1

array([9, 1, 6, 8, 8, 3, 2, 3, 6, 3])

In [38]:
x1[3]

8

In [39]:
x2 = np.random.randint(20,size = (3,4))
x2

array([[ 5, 11,  0, 11],
       [ 8, 10, 11,  5],
       [15,  8,  2, 19]])

In [40]:
x2[1,2]

11

In [41]:
x1[1:8:2]

array([1, 8, 3, 3])

In [42]:
x1[0:3]

array([9, 1, 6])

In [44]:
x2[:2,:3]

array([[ 5, 11,  0],
       [ 8, 10, 11]])

## Reshape + Transpose

In [46]:
x2.reshape((2,6))

array([[ 5, 11,  0, 11,  8, 10],
       [11,  5, 15,  8,  2, 19]])

In [47]:
x2.T

array([[ 5,  8, 15],
       [11, 10,  8],
       [ 0, 11,  2],
       [11,  5, 19]])

## Array Concatenation and Splitting

In [48]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [50]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [52]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [53]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [55]:
y = np.array([[99],
              [99]])
np.hstack([y, grid])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [56]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


## Broadcasting and Vectorized operations
Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.

In [59]:
a = np.arange(3)
a

array([0, 1, 2])

In [60]:
a + 5

array([5, 6, 7])

In [61]:
a * 10

array([ 0, 10, 20])

In [62]:
a += 100

In [63]:
l = [0, 1, 2, 3]

In [64]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [66]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [67]:
b = np.array([10, 10, 10, 10])
b

array([10, 10, 10, 10])

In [68]:
a + b

array([10, 11, 12, 13])

In [69]:
a*b

array([ 0, 10, 20, 30])

## Sorting Arrays
used quicksort

In [70]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [74]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x) # trả về index sau khi sort
i

array([1, 0, 3, 2, 4], dtype=int64)

In [77]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4,4))
X

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7],
       [7, 2, 5, 4]])

In [78]:
np.sort(X, axis=0)
# sort theo hàng

array([[6, 2, 2, 4],
       [6, 3, 3, 4],
       [7, 4, 5, 6],
       [7, 9, 7, 7]])

In [79]:
np.sort(X, axis=1)
# sort theo cột

array([[3, 4, 6, 7],
       [2, 6, 6, 9],
       [3, 4, 7, 7],
       [2, 4, 5, 7]])

## Linear Algebra

In [80]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [81]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [82]:
A.dot(B) # tích vô hướng

array([[20, 14],
       [56, 41],
       [92, 68]])

In [83]:
A @ B # như dot

array([[20, 14],
       [56, 41],
       [92, 68]])

In [84]:
B.T


array([[6, 4, 2],
       [5, 3, 1]])